//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.25 at 09:16:37 PM PDT 
//


package com.freepublicblogs.common.blog;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.freepublicblogs.common.blog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Blog_QNAME = new QName("https://www.publicBlog.com/Schemas", "Blog");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.freepublicblogs.common.blog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Blog }
     * 
     */
    public Blog createBlog() {
        return new Blog();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Blog }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.publicBlog.com/Schemas", name = "Blog")
    public JAXBElement<Blog> createBlog(Blog value) {
        return new JAXBElement<Blog>(_Blog_QNAME, Blog.class, null, value);
    }

}
